version: "3.4"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    network_mode: host
  kafka-broker:
    image: wurstmeister/kafka:2.12-2.0.1
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: "hostname -i"
      KAFKA_CREATE_TOPICS: "<YOUR TOPIC HERE>:1:1,<YOUR TOPIC HERE>:1:1,<YOUR TOPIC HERE>:1:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    network_mode: host
  master:
    build:
      context: statefun-config
    expose:
      - "6123"
    ports:
      - "8081:8081"
      - "6123:6123"
    environment:
      - ROLE=master
    volumes:
      - ./checkpoint-dir:/checkpoint-dir
    network_mode: host
  worker:
    build:
      context: statefun-config
    expose:
      - "6121"
      - "6122"
    depends_on:
      - master
      - kafka-broker
    network_mode: host
    environment:
      - ROLE=worker
    volumes:
      - ./checkpoint-dir:/checkpoint-dir